version: "2.4"
services:
  app:
    build:
      context: .
    container_name: app
    environment:
      DB_LOCAL: 'disabled'
      WEB_DRIVER_REMOTE_URL: 'http://selenium:4444/wd/hub'
      DB_URL: 'postgresql://postgres:postgres@postgres:5432/postgres'
    ports:
    - "8000:8000"
    depends_on:
      - selenium
      - postgres
    restart: on-failure
    networks:
      - network_deploy
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - selenium
    ports:
      - "5432:5432"
    networks:
      - network_deploy
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    networks:
      - network_deploy
networks:
  network_deploy:
    name: network_deploy



