FROM browserless/chrome:latest

WORKDIR /app

COPY . .

RUN apt update -y && apt install python3 python3-pip -y

RUN pip install --no-cache-dir --upgrade -r ./requirements.txt


CMD ["python3", "-m", "uvicorn webapp.main:app","--reload"]