name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      run: aws ecr get-login-password --region ${{ secrets.AWS_ECR_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_URL }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.AWS_ECR_NAME }} .
        docker tag ${{ secrets.AWS_ECR_NAME }}:latest ${{ secrets.AWS_ECR_URL }}/${{ secrets.AWS_ECR_NAME }}:latest

    - name: Push Docker image to Amazon ECR
      run: docker push ${{ secrets.AWS_ECR_URL }}/${{ secrets.AWS_ECR_NAME }}:latest
